sonar.projectKey={{ cookiecutter.project_slug }}
sonar.projectName={{ cookiecutter.project_name }}
sonar.projectVersion=0.1.0

sonar.sources=app
sonar.tests=tests
sonar.language=py
sonar.python.version={{ cookiecutter.python_version }}

sonar.python.coverage.reportPaths=coverage.xml
sonar.python.xunit.reportPath=test-results.xml

sonar.sourceEncoding=UTF-8
sonar.exclusions=**/migrations/**,**/__pycache__/**
sonar.test.exclusions=tests/**
{%- if cookiecutter.quality_gate == "sonarcloud" %}

sonar.organization=your-org
sonar.host.url=https://sonarcloud.io
{%- endif %}
